---
- name: Demo DaemonSets
  hosts: demo
  connection: local
  gather_facts: false
  vars:
    namespace: logging
  tasks:
    - name: Create daemonset-admin ClusterRole
      k8s_resource:
        resource_desc:
          apiVersion: v1
          kind: ClusterRole
          metadata:
            name: daemonset-admin
          rules:
          - resources:
            - daemonsets
            apiGroups:
            - extensions
            verbs:
            - create
            - get
            - list
            - watch
            - delete
            - update

    - name: Create ServiceAccount
      k8s_resource:
        resource_desc:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: aggregated-logging-fluentd
            namespace: "{{ namespace }}"
            labels:
              logging-infra: fluentd

    - name: "oc adm policy add-role-to-user daemonset-admin system:serviceaccount:{{ logging_project }}:aggregated-logging-fluentd"
      k8s_resource:
        resource_desc:
          apiVersion: v1
          kind: RoleBinding
          metadata:
            name: daemonset-admin
            namespace: default
          roleRef:
            name: daemonset-admin
          subjects:
          - kind: ServiceAccount
            name: aggregated-logging-fluentd
            namespace: "{{ namespace }}"
          userNames:
          - "system:serviceaccount:{{ namespace }}:aggregated-logging-fluentd"

    - name: Deploy Fluentd Daemonset
      k8s_resource:
        resource_desc:
          apiVersion: extensions/v1beta1
          kind: "DaemonSet"
          metadata:
            name: "logging-fluentd"
            namespace: "{{ namespace }}"
            labels:
              provider: openshift
              logging-infra: fluentd
          spec:
            selector:
              matchLabels:
                component: "fluentd"
            template:
              metadata:
                name: fluentd-nodecollector
                labels:
                  provider: openshift
                  component: "fluentd"
              spec:
                terminationGracePeriodSeconds: 300
                serviceAccountName: aggregated-logging-fluentd
                nodeSelector:
                  logging-infra: fluentd
                containers:
                - name: fluentd-collector
                  image: atomic-registry.usersys.redhat.com:5000/t0ffel/logging-fluentd:latest
                  imagePullPolicy: Always
                  securityContext:
                    privileged: true
                  resources:
                    limits:
                      cpu: 100m
                  volumeMounts:
                  - name: runlogjournal
                    mountPath: /run/log/journal
                  - name: varlog
                    mountPath: /var/log
                  - name: varlibdockercontainers
                    mountPath: /var/lib/docker/containers
                    readOnly: true
                  - name: dockerhostname
                    mountPath: /etc/docker-hostname
                    readOnly: true
                  - name: localtime
                    mountPath: /etc/localtime
                    readOnly: true
                  - name: dockercfg
                    mountPath: /etc/sysconfig/docker
                    readOnly: true
                  - name: fluent-entrypoint
                    mountPath: /etc/fluent/entrypoint
                    readOnly: true
                  - name: fluent-input
                    mountPath: /etc/fluent/input
                    readOnly: true
                  - name: fluent-journal
                    mountPath: /etc/fluent/journal
                    readOnly: true
                  - name: fluent-catchall
                    mountPath: /etc/fluent/catchall
                    readOnly: true
                  env:
                  - name: "K8S_HOST_URL"
                    value: https://kubernetes.default.svc.cluster.local
                volumes:
                - name: runlogjournal
                  hostPath:
                    path: /run/log/journal
                - name: varlog
                  hostPath:
                    path: /var/log
                - name: varlibdockercontainers
                  hostPath:
                    path: /var/lib/docker/containers
                - name: dockerhostname
                  hostPath:
                    path: /etc/hostname
                - name: localtime
                  hostPath:
                    path: /etc/localtime
                - name: dockercfg
                  hostPath:
                    path: /etc/sysconfig/docker
                - name: fluent-entrypoint
                  configMap:
                    name: fluent-entrypoint-cm
                - name: fluent-input
                  configMap:
                    name: fluent-input-cm
                - name: fluent-journal
                  configMap:
                    name: fluent-journal-cm
                - name: fluent-catchall
                  configMap:
                    name: fluent-catchall-cm

    - name: Add SA to privileged SCC
      k8s_contains:
        target_resource:
          apiVersion: v1
          kind: SecurityContextConstraints
          metadata:
            name: privileged
        patch:
          users:
          - "system:serviceaccount:{{ namespace }}:aggregated-logging-fluentd"

    - name: "oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:{{ logging_project }}:aggregated-logging-fluentd"
      k8s_contains:
        target_resource:
          apiVersion: v1
          kind: ClusterRoleBinding
          metadata:
            name: cluster-readers
        patch:
          userNames:
          - "system:serviceaccount:{{ namespace }}:aggregated-logging-fluentd"
          subjects:
          - kind: ServiceAccount
            namespace: "{{ namespace }}"
            name: aggregated-logging-fluentd
